# Site settings
title: Herro!
email: anita13benita@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  MEOW
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tridentwizard.com" # the base hostname & protocol for your site
twitter_username: tridentwizard
github_username:  tridentwizard

# Build settings
markdown: kramdown
